version: '3.8'

services:
  
  backend:
    image: ${webdotg}
    container_name: ${webdotg}
    restart: always
    env_file:
      - .env
    ports:
      - "1111:1111"
    depends_on:
      - postgres
    networks:
      - project

  postgres:
    image: postgres:alpine
    
    restart: always
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - project

    volumes:
       - ./data:/var/lib/postgresql/data

networks:
  project:
     driver: bridge
